#!/usr/bin/env python3
"""AI Commit Translator CLI — 入口文件"""
import click
from .translate import translate

@click.group()
@click.version_option("1.0.0")
def cli():
    """📝 AI Commit Translator — 中文需求 → 规范英文 Commit"""
    pass


cli.add_command(translate)


@cli.command()
def install_hook():
    """🪝 安装 git commit-msg hook"""
    import os
    import sys

    hook_path = ".git/hooks/commit-msg"
    hook_dir = ".git/hooks"

    if not os.path.exists(".git"):
        click.echo("❌ 当前目录不是 Git 仓库")
        sys.exit(1)

    os.makedirs(hook_dir, exist_ok=True)

    hook_content = """#!/bin/sh
# AI Commit Translator Hook
# Generated by ai-commit-translator

INPUT_FILE=$1

# 读取原始 message
ORIGINAL_MSG=$(cat "$INPUT_FILE")

# 如果是空 message 或只有前缀，自动生成
if [ -z "$ORIGINAL_MSG" ] || echo "$ORIGINAL_MSG" | grep -q "^[a-zA-Z0-9_]+("; then
    echo "$ORIGINAL_MSG"
    exit 0
fi

# 调用 AI 翻译
TRANSLATED=$(echo "$ORIGINAL_MSG" | ai-commit translate --provider openai 2>/dev/null)

if [ -n "$TRANSLATED" ]; then
    echo "$TRANSLATED" > "$INPUT_FILE"
    echo "✅ AI 已优化 commit message"
fi
"""

    with open(hook_path, "w") as f:
        f.write(hook_content)

    os.chmod(hook_path, 0o755)
    click.echo(f"✅ Hook 已安装: {hook_path}")


@cli.command()
def uninstall_hook():
    """🗑️ 卸载 git commit-msg hook"""
    import os
    import sys

    hook_path = ".git/hooks/commit-msg"

    if os.path.exists(hook_path):
        os.remove(hook_path)
        click.echo("✅ Hook 已卸载")
    else:
        click.echo("⚠️  Hook 不存在")


if __name__ == "__main__":
    cli()
